config/routes.rb
Rails.application.routes.draw do

  root 'recommendations#index'

  controller 'recommendations' do
    get 'recommendation', action: 'index'
    get 'recommendations(/*previous_ids)/:id', action: 'show', as: 'recommendations'
  end

  get "log_out", to: "sessions#destroy"
  get "log_in", to: "sessions#new"
  get "sign_up", to: "users#new"

  resources :users
  resources :sessions

end

app/models/node.rb
class Node < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :total_visits, numericality: { greater_than_or_equal_to: 0 }

  def probability_hash
    Hash[Path.where(begin_node_id: id).map { |x| [x.end_node_id, x.total_traversals.to_f/total_visits]}]
  end

  def combined_probability prev_hash
    combined = probability_hash.keep_if { |k, v| prev_hash.has_key? k } # use slice!
    normalized combined.each_key { |k| combined[k] *= prev_hash[k]}
  end

  def normalized hash
    normalizing_constant = hash.values.inject(:+)
    hash.each_key { |k| hash[k] /= normalizing_constant}
  end
end

app/models/path.rb
class Path < ActiveRecord::Base
  validates :end_node_id, presence: true
  validate :existence_of_end_node, on: [:create]
  validate :uniqueness_of_node_pair, on: [:create]
  after_update :update_node_visits

  def self.find_by_node_pair(b, e)
    find_by(begin_node_id: b, end_node_id: e)
  end

  def self.node_pair_exists?(b, e)
    !find_by_node_pair(b, e).nil?
  end

  def begin_node
    Node.find(begin_node_id)
  end

  def end_node
    Node.find(end_node_id)
  end

  private

  def update_node_visits
    unless begin_node_id.nil?
      node = begin_node
      node.total_visits += 1
      node.save!
    end
  end

  def existence_of_end_node
    node = begin
      Node.find(end_node_id)
    rescue Exception => e
      nil
    end
    if node.nil?
      errors.add(:end_node_existence, "End node does not exist!")
    end
  end

  def uniqueness_of_node_pair
    if Path.node_pair_exists?(begin_node_id, end_node_id)
      errors.add(:path_uniqueness, "Path already exists")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  before_save :encrypt_password

  validates :password, confirmation: true
  validates :password, presence: true, on: :create
  validates :email, presence: true
  validates :email, uniqueness: true

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def password=(unencrypted_password)
    unless unencrypted_password.blank?
      @password = unencrypted_password
    end
  end

  def password_confirmation=(unencrypted_password)
    @password_confirmation = unencrypted_password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    if current_user.nil?
      redirect_to log_in_path
    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @nodes = Node.all
  end

  def show
    path = !params[:previous_ids].nil? ? params[:previous_ids].split('/') : []
    path.push(params[:id]).map! { |x| x.to_i }

    # Sanity Check, @todo: better fix later.
    if sanity_check(path)
      render(status: 400, json: { errors: 'Bad input' })
    else
      recommended_nodes = recommended_array generate_probability_hash(path.clone)
      @nodes = recommended_nodes.map {|x| { id: x.first, name: Node.find(x.first).name, score: x.last } }
      @path = path
    end
  end

  private

  def generate_probability_hash ids
    node_id = ids.pop
    return Node.find(node_id).probability_hash if ids.empty?
    previous_recommendation_hash = generate_probability_hash ids
    Node.find(node_id).combined_probability previous_recommendation_hash
  end

  def recommended_array hash
    hash.to_a.sort{ |x, y| x.last <=> y.last }.reverse
  end

  def sanity_check path
    return true if path.max > Node.all.size
    return true if path.min < 0
    return true unless path.clone.keep_if { |x| y = x.to_i; (y > 0) && y.integer? }.size == path.size
    false
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Markov</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user %>
    Logged in as <b><%= current_user.email %></b> &mdash;
    <%= link_to "Log Out", log_out_path %>
  <% else %>
    <%= link_to "Sign Up", sign_up_path %> or
    <%= link_to "Log In", log_in_path %>
  <% end %>
</div>

<div id="flash_messages">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}", class: "flash_message" %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/recommendations/index.html.haml
%h1 People

- if @nodes.any?
  %table
    %tr
      %th Name
      %th Views
      %th Recommendations
    - @nodes.each do |node|
      %tr
        %td= node.name
        %td= node.total_visits
        %td= link_to "Recommend Me", recommendations_path(id: node.id, format: :json)

app/views/users/new.html.haml
%h1 Sign Up

= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2 #{pluralize(@movie.errors.count, "error")} prohibited this movie from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message


  .field
    = f.label :email
    %br
    = f.email_field :email
  .field
    = f.label :password
    %br
    = f.password_field :password
  .field
    = f.label :password_confirmation
    %br
    = f.password_field :password_confirmation
  .actions
    = f.submit